export const knownAuditActions = [
  'TENANT_CREATED', 'TENANT_STATUS_CHANGED', 'STORE_UPDATED', 'STORE_STATUS_CHANGED',
  'EMPLOYEE_CREATED', 'EMPLOYEE_ROLE_CHANGED', 'EMPLOYEE_STATUS_CHANGED', 'EMPLOYEE_PASSWORD_RESET',
  'KIOSK_DEVICE_REGISTERED', 'KIOSK_CREDENTIAL_ROTATED', 'KIOSK_DEVICE_REVOKED',
  'KIOSK_DEVICE_MODE_CHANGED', 'KIOSK_DEVICE_PAYMENT_PAIR_CHANGED', 'TABLE_CREATED', 'TABLE_UPDATED',
  'TABLE_STATUS_CHANGED', 'CATEGORY_CHANGED', 'PRODUCT_CHANGED', 'PRODUCT_PRICE_CHANGED',
  'PRODUCT_SOLD_OUT_CHANGED', 'ORDER_CREATED', 'ORDER_ACCEPTED', 'ORDER_CANCELLED', 'ORDER_COMPLETED',
  'BUSINESS_DAY_CLOSED', 'ORDER_TABLE_ASSIGNED', 'TABLE_SESSION_OPENED',
  'TABLE_SESSION_CHECKOUT_STARTED', 'TABLE_SESSION_CLOSED', 'OUTBOX_ROW_RECOVERED',
  'PAYMENT_APPROVED', 'PAYMENT_CANCELLED', 'PAYMENT_REVIEW_REQUIRED', 'PAYMENT_HANDOFF_CREATED',
  'PAYMENT_BATCH_APPROVED', 'PAYMENT_BATCH_CANCELLED', 'PAYMENT_HANDOFF_REISSUED',
  'PAYMENT_HANDOFF_REASSIGNED', 'PAYMENT_HANDOFF_EXPIRED', 'PAYMENT_HANDOFF_CANCELLED',
  'ENTRY_REGISTERED', 'ENTRY_ENTERED', 'ENTRY_CANCELLED', 'ENTRY_NO_SHOW', 'FULFILLMENT_CREATED',
  'FULFILLMENT_READY', 'FULFILLMENT_CANCELLED',
] as const

export const knownAuditTargetTypes = [
  'TENANT', 'STORE', 'EMPLOYEE', 'KIOSK_DEVICE', 'STORE_TABLE', 'CATEGORY', 'PRODUCT', 'ORDER',
  'DAILY_CLOSING', 'TABLE_SESSION', 'AUDIT_OUTBOX_ROW', 'PAYMENT', 'PAYMENT_HANDOFF', 'ENTRY_QUEUE',
  'FULFILLMENT',
] as const

export type KnownAuditAction = (typeof knownAuditActions)[number]
export type KnownAuditTargetType = (typeof knownAuditTargetTypes)[number]
